In [48]:
import numpy as np
import sys
Insurance_Data = np.genfromtxt('insurance.csv',delimiter =',',dtype = object)
#np.set_printoptions(threshold=sys.maxsize)
Insurance_Data

array([[b'age', b'sex', b'bmi', b'children', b'smoker', b'region',
        b'charges'],
       [b'19', b'female', b'27.9', b'0', b'yes', b'southwest',
        b'16884.924'],
       [b'18', b'male', b'33.77', b'1', b'no', b'southeast',
        b'1725.5523'],
       [b'28', b'male', b'33', b'3', b'no', b'southeast', b'4449.462'],
       [b'33', b'male', b'22.705', b'0', b'no', b'northwest',
        b'21984.47061'],
       [b'32', b'male', b'28.88', b'0', b'no', b'northwest',
        b'3866.8552'],
       [b'31', b'female', b'25.74', b'0', b'no', b'southeast',
        b'3756.6216'],
       [b'46', b'female', b'33.44', b'1', b'no', b'southeast',
        b'8240.5896'],
       [b'37', b'female', b'27.74', b'3', b'no', b'northwest',
        b'7281.5056'],
       [b'37', b'male', b'29.83', b'2', b'no', b'northeast',
        b'6406.4107'],
       [b'60', b'female', b'25.84', b'0', b'no', b'northwest',
        b'28923.13692'],
       [b'25', b'male', b'26.22', b'0', b'no', b'northeast',
        

In [54]:
Age = Insurance_Data[1:,0]
Age = Age.astype('int')
           
print('Mean', np.mean(Age))
print('Median', np.median(Age))
print('Standard Deviation', np.std(Age))
Age

Mean 39.20702541106129
Median 39.0
Standard Deviation 14.044709038954522


array([19, 18, 28, 33, 32, 31, 46, 37, 37, 60, 25, 62, 23, 56, 27, 19, 52,
       23, 56, 30, 60, 30, 18, 34, 37, 59, 63, 55, 23, 31, 22, 18, 19, 63,
       28, 19, 62, 26, 35, 60, 24, 31, 41, 37, 38, 55, 18, 28, 60, 36, 18,
       21, 48, 36, 40, 58, 58, 18, 53, 34, 43, 25, 64, 28, 20, 19, 61, 40,
       40, 28, 27, 31, 53, 58, 44, 57, 29, 21, 22, 41, 31, 45, 22, 48, 37,
       45, 57, 56, 46, 55, 21, 53, 59, 35, 64, 28, 54, 55, 56, 38, 41, 30,
       18, 61, 34, 20, 19, 26, 29, 63, 54, 55, 37, 21, 52, 60, 58, 29, 49,
       37, 44, 18, 20, 44, 47, 26, 19, 52, 32, 38, 59, 61, 53, 19, 20, 22,
       19, 22, 54, 22, 34, 26, 34, 29, 30, 29, 46, 51, 53, 19, 35, 48, 32,
       42, 40, 44, 48, 18, 30, 50, 42, 18, 54, 32, 37, 47, 20, 32, 19, 27,
       63, 49, 18, 35, 24, 63, 38, 54, 46, 41, 58, 18, 22, 44, 44, 36, 26,
       30, 41, 29, 61, 36, 25, 56, 18, 19, 39, 45, 51, 64, 19, 48, 60, 27,
       46, 28, 59, 35, 63, 40, 20, 40, 24, 34, 45, 41, 53, 27, 26, 24, 34,
       53, 32, 19, 42, 55

In [58]:

data = np.genfromtxt('insurance.csv', delimiter=',', skip_header=1, 
                          usecols = [-1], dtype = object)
data

array([b'16884.924', b'1725.5523', b'4449.462', b'21984.47061',
       b'3866.8552', b'3756.6216', b'8240.5896', b'7281.5056',
       b'6406.4107', b'28923.13692', b'2721.3208', b'27808.7251',
       b'1826.843', b'11090.7178', b'39611.7577', b'1837.237',
       b'10797.3362', b'2395.17155', b'10602.385', b'36837.467',
       b'13228.84695', b'4149.736', b'1137.011', b'37701.8768',
       b'6203.90175', b'14001.1338', b'14451.83515', b'12268.63225',
       b'2775.19215', b'38711', b'35585.576', b'2198.18985', b'4687.797',
       b'13770.0979', b'51194.55914', b'1625.43375', b'15612.19335',
       b'2302.3', b'39774.2763', b'48173.361', b'3046.062', b'4949.7587',
       b'6272.4772', b'6313.759', b'6079.6715', b'20630.28351',
       b'3393.35635', b'3556.9223', b'12629.8967', b'38709.176',
       b'2211.13075', b'3579.8287', b'23568.272', b'37742.5757',
       b'8059.6791', b'47496.49445', b'13607.36875', b'34303.1672',
       b'23244.7902', b'5989.52365', b'8606.2174', b'4504.6624',
  

In [60]:
iris_data = np.genfromtxt('insurance.csv', delimiter=',', skip_header=1, dtype='float', usecols=[0,1,2,3])
iris_data

array([[19.   ,    nan, 27.9  ,  0.   ],
       [18.   ,    nan, 33.77 ,  1.   ],
       [28.   ,    nan, 33.   ,  3.   ],
       [33.   ,    nan, 22.705,  0.   ],
       [32.   ,    nan, 28.88 ,  0.   ],
       [31.   ,    nan, 25.74 ,  0.   ],
       [46.   ,    nan, 33.44 ,  1.   ],
       [37.   ,    nan, 27.74 ,  3.   ],
       [37.   ,    nan, 29.83 ,  2.   ],
       [60.   ,    nan, 25.84 ,  0.   ],
       [25.   ,    nan, 26.22 ,  0.   ],
       [62.   ,    nan, 26.29 ,  0.   ],
       [23.   ,    nan, 34.4  ,  0.   ],
       [56.   ,    nan, 39.82 ,  0.   ],
       [27.   ,    nan, 42.13 ,  0.   ],
       [19.   ,    nan, 24.6  ,  1.   ],
       [52.   ,    nan, 30.78 ,  1.   ],
       [23.   ,    nan, 23.845,  0.   ],
       [56.   ,    nan, 40.3  ,  0.   ],
       [30.   ,    nan, 35.3  ,  0.   ],
       [60.   ,    nan, 36.005,  0.   ],
       [30.   ,    nan, 32.4  ,  1.   ],
       [18.   ,    nan, 34.1  ,  0.   ],
       [34.   ,    nan, 31.92 ,  1.   ],
       [37.   , 

In [102]:
iris_data = np.genfromtxt('insurance.csv', delimiter=',', dtype='float', usecols=[0,2,3], skip_header=1)
for i in np.random.randint(0, len(iris_data), 20):
    iris_data[i]=np.nan
iris_data

array([[19.   , 27.9  ,  0.   ],
       [18.   , 33.77 ,  1.   ],
       [28.   , 33.   ,  3.   ],
       [33.   , 22.705,  0.   ],
       [32.   , 28.88 ,  0.   ],
       [31.   , 25.74 ,  0.   ],
       [46.   , 33.44 ,  1.   ],
       [37.   , 27.74 ,  3.   ],
       [37.   , 29.83 ,  2.   ],
       [60.   , 25.84 ,  0.   ],
       [25.   , 26.22 ,  0.   ],
       [62.   , 26.29 ,  0.   ],
       [23.   , 34.4  ,  0.   ],
       [56.   , 39.82 ,  0.   ],
       [   nan,    nan,    nan],
       [19.   , 24.6  ,  1.   ],
       [52.   , 30.78 ,  1.   ],
       [23.   , 23.845,  0.   ],
       [56.   , 40.3  ,  0.   ],
       [30.   , 35.3  ,  0.   ],
       [60.   , 36.005,  0.   ],
       [30.   , 32.4  ,  1.   ],
       [18.   , 34.1  ,  0.   ],
       [34.   , 31.92 ,  1.   ],
       [37.   , 28.025,  2.   ],
       [59.   , 27.72 ,  3.   ],
       [63.   , 23.085,  0.   ],
       [55.   , 32.775,  2.   ],
       [23.   , 17.385,  1.   ],
       [31.   , 36.3  ,  2.   ],
       [22

In [63]:
np.random.randint(0,40,5)

array([31, 39, 17, 19,  7])

In [64]:
np.random.randint(len(iris_data), size=20)

array([ 954,  446,  998,   48, 1275,  616, 1201,  848,  253,  418,  103,
        684,  650,  162,  693, 1180,  207,  673, 1239,  124])

In [65]:
len(iris_data)

1338

In [66]:
np.random.randint(4,size=20)

array([1, 0, 2, 3, 3, 3, 2, 2, 1, 1, 3, 0, 0, 1, 0, 2, 3, 1, 2, 3])

In [105]:
iris_data = np.genfromtxt('insurance.csv', delimiter=',', dtype='float', usecols=[0,2,3], skip_header=1)

iris_data[np.random.randint(len(iris_data), size=20),np.random.randint(2,size=20)] = np.nan

print(iris_data)


# Find total mising value in complete data
print("Number of missing values in Iris data: \n", np.isnan(iris_data[:, :]).sum())

# Find total mising value in 1D data
print("Number of missing values in any one feature of Iris data: \n", np.isnan(iris_data[:, 0]).sum())

print("Position of missing values: \n", np.where(np.isnan(iris_data[:, 0])))

1.0
Number of missing values in Iris data: 
 0
Number of missing values in any one feature of Iris data: 
 0
Position of missing values: 
 (array([], dtype=int64),)


In [127]:
diabetes_data = np.genfromtxt('insurance.csv', delimiter=',', dtype='float', usecols=[0,2,3], skip_header=1)
diabetes_data[np.random.randint(150, size=20), np.random.randint(2, size=20)] = np.nan


diabetes_data[np.sum(np.isnan(diabetes_data), axis = 1) == 0][:5]

array([[19.   , 27.9  ,  0.   ],
       [18.   , 33.77 ,  1.   ],
       [28.   , 33.   ,  3.   ],
       [33.   , 22.705,  0.   ],
       [32.   , 28.88 ,  0.   ]])

In [94]:
#len(diabetes_data[np.sum(np.isnan(diabetes_data), axis = 1) == 0])

1321

In [99]:

insurance = np.genfromtxt('insurance.csv',
                             delimiter=',', dtype=object, usecols=[0], skip_header=1)

np.unique(insurance)
# return_counts=True

array([b'18', b'19', b'20', b'21', b'22', b'23', b'24', b'25', b'26',
       b'27', b'28', b'29', b'30', b'31', b'32', b'33', b'34', b'35',
       b'36', b'37', b'38', b'39', b'40', b'41', b'42', b'43', b'44',
       b'45', b'46', b'47', b'48', b'49', b'50', b'51', b'52', b'53',
       b'54', b'55', b'56', b'57', b'58', b'59', b'60', b'61', b'62',
       b'63', b'64'], dtype=object)

In [122]:
np.random.randint(2,size=20)

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [110]:
np.random.randint(150, size=20)

array([ 98, 132,   9, 148,  79, 140,  49,   1,  18,  14,  96,  18,  22,
       124,  16,  30,  90,  10, 145,   7])

In [132]:
np.sum(np.isnan(diabetes_data))

20

In [141]:
np.sum((np.isnan(diabetes_data)).astype(int))

diabetes_data[np.sum(np.isnan(diabetes_data), axis = 1)]

array([[19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [18.  , 33.77,  1.  ],
       [19.  , 27.9 ,  0.  ],
       [18.  , 33.77,  1.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [18.  , 33.77,  1.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [18.  , 33.77,  1.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [18.  , 33.77,  1.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [19.  , 27.9 ,  0.  ],
       [18